/**
 * The demo registry: the open agent ecosystem, one row per entry.
 *
 * Six kinds, five crafts. Every name, command, and URL points at something
 * real. `addedAt` dates are sample catalog data for the demo, and the
 * install commands are illustrative: wire them to a live registry before
 * shipping (the UI says so too).
 */

export const KINDS = ['skill', 'mcp', 'api', 'protocol', 'harness', 'software'] as const

export type Kind = (typeof KINDS)[number]

export const CRAFTS = ['Design', 'DevEx', 'Content', 'Research', 'Multimedia'] as const

export type Craft = (typeof CRAFTS)[number]

export interface RegistryEntry {
  slug: string
  name: string
  kind: Kind
  craft: Craft
  tagline: string
  description: string
  /** Natural language or search terms that surface this entry. */
  triggers: string[]
  /** The single thing worth copying: a command, an endpoint, or a spec link. */
  command: string
  /** What the command is. Keeps the UI honest about what it actually does. */
  commandLabel: string
  /** Canonical home: repository, docs, or product site. */
  url: string
  urlLabel: string
  /** Only filled where the licence is known and stable. */
  license?: string
  /** Date the entry was added to this registry. Sample catalog data. */
  addedAt: string
  featured?: boolean
}

export const KIND_META: Record<Kind, { label: string; blurb: string }> = {
  skill: {
    label: 'Skill',
    blurb:
      'A SKILL.md folder that teaches an agent one capability. Markdown you can read before you run it.',
  },
  mcp: {
    label: 'MCP server',
    blurb:
      'A tool server that speaks the Model Context Protocol, so any MCP client can call it without bespoke glue.',
  },
  api: {
    label: 'Public API',
    blurb:
      'An HTTP API you can call directly from an agent, a script, or a serverless function. Keys where required.',
  },
  protocol: {
    label: 'Protocol',
    blurb:
      'A wire format or contract that lets independent agents, tools, and editors understand each other.',
  },
  harness: {
    label: 'Harness',
    blurb:
      'The loop that runs an agent: plans, calls tools, edits files, and reports back. Where skills actually execute.',
  },
  software: {
    label: 'Free software',
    blurb:
      'Open-source runtimes, databases, and inference engines you can self-host. No vendor between you and the model.',
  },
}

const SKILLS: RegistryEntry[] = [
  {
    slug: 'design-taste-frontend',
    name: 'design-taste-frontend',
    kind: 'skill',
    craft: 'Design',
    tagline: 'Anti-slop audits for landing pages.',
    description:
      'Reviews a page against a production checklist: typography discipline, color locks, layout repetition bans, and accessibility guardrails. Catches the AI-default patterns before they ship.',
    triggers: ['landing page', 'redesign', 'hero section', 'design audit', 'pre-flight check'],
    command: 'npx skills add design-taste-frontend',
    commandLabel: 'Install',
    url: 'https://github.com/aniruddhaadak/wow-repo',
    urlLabel: 'Demo catalog',
    addedAt: '2026-10-02',
    featured: true,
  },
  {
    slug: 'brand-palette-lock',
    name: 'brand-palette-lock',
    kind: 'skill',
    craft: 'Design',
    tagline: 'One accent color, audited everywhere.',
    description:
      'Picks a single accent and locks it across every component, mode, and state. Flags stray hues and off-palette calls to action before they reach production.',
    triggers: ['color palette', 'accent color', 'design tokens', 'theme consistency'],
    command: 'npx skills add brand-palette-lock',
    commandLabel: 'Install',
    url: 'https://github.com/aniruddhaadak/wow-repo',
    urlLabel: 'Demo catalog',
    addedAt: '2026-09-21',
  },
  {
    slug: 'video-ad-specs',
    name: 'video-ad-specs',
    kind: 'skill',
    craft: 'Multimedia',
    tagline: 'Exact platform specs for video ads.',
    description:
      'Carries the real dimensions, duration caps, and caption rules for TikTok, Instagram, YouTube, Facebook, and LinkedIn, plus the AIDA structure that fits inside them.',
    triggers: ['video ad', 'tiktok ad', 'reels ad', 'ad specs', 'paid media'],
    command: 'npx skills add video-ad-specs',
    commandLabel: 'Install',
    url: 'https://github.com/aniruddhaadak/wow-repo',
    urlLabel: 'Demo catalog',
    addedAt: '2026-09-14',
  },
  {
    slug: 'youtube-thumbnail-design',
    name: 'youtube-thumbnail-design',
    kind: 'skill',
    craft: 'Multimedia',
    tagline: 'Thumbnails that survive the mobile preview.',
    description:
      'Designs inside the safe zone, plans contrast for a 120px-wide preview, and sets up the A/B test instead of guessing at what clicked.',
    triggers: ['youtube thumbnail', 'thumbnail design', 'click-through rate', 'video cover'],
    command: 'npx skills add youtube-thumbnail-design',
    commandLabel: 'Install',
    url: 'https://github.com/aniruddhaadak/wow-repo',
    urlLabel: 'Demo catalog',
    addedAt: '2026-09-16',
  },
  {
    slug: 'vercel-edge-optimizer',
    name: 'vercel-edge-optimizer',
    kind: 'skill',
    craft: 'DevEx',
    tagline: 'Tune Next.js builds for the edge.',
    description:
      'Audits rendering strategy, bundle budgets, and cache headers for a Vercel deploy, then returns a prioritized list with the expected effect on LCP and INP.',
    triggers: ['next.js', 'core web vitals', 'edge functions', 'bundle size', 'caching'],
    command: 'npx skills add vercel-edge-optimizer',
    commandLabel: 'Install',
    url: 'https://github.com/aniruddhaadak/wow-repo',
    urlLabel: 'Demo catalog',
    addedAt: '2026-09-28',
    featured: true,
  },
  {
    slug: 'code-review-cadence',
    name: 'code-review-cadence',
    kind: 'skill',
    craft: 'DevEx',
    tagline: 'Maintainer-grade review checklists.',
    description:
      'Structures a pull request review around bugs, security, performance, and test gaps, and writes feedback a maintainer can act on without a follow-up thread.',
    triggers: ['code review', 'pull request', 'pr feedback', 'review checklist'],
    command: 'npx skills add code-review-cadence',
    commandLabel: 'Install',
    url: 'https://github.com/aniruddhaadak/wow-repo',
    urlLabel: 'Demo catalog',
    addedAt: '2026-09-25',
  },
  {
    slug: 'oss-ship-kit',
    name: 'oss-ship-kit',
    kind: 'skill',
    craft: 'DevEx',
    tagline: 'Issue to merged PR, end to end.',
    description:
      'Picks an issue, branches cleanly, implements test-first, and prepares the PR with a conventional commit and a description that links the issue.',
    triggers: ['open source', 'contribute', 'first issue', 'pull request'],
    command: 'npx skills add oss-ship-kit',
    commandLabel: 'Install',
    url: 'https://github.com/aniruddhaadak/wow-repo',
    urlLabel: 'Demo catalog',
    addedAt: '2026-09-19',
  },
  {
    slug: 'prisma-schema-mentor',
    name: 'prisma-schema-mentor',
    kind: 'skill',
    craft: 'DevEx',
    tagline: 'Schema design, reviewed.',
    description:
      'Reads a Prisma schema for indexing, relation cardinality, and migration safety, then suggests the indexes and refactors before slow queries reach production.',
    triggers: ['prisma', 'schema design', 'database indexing', 'migration'],
    command: 'npx skills add prisma-schema-mentor',
    commandLabel: 'Install',
    url: 'https://github.com/aniruddhaadak/wow-repo',
    urlLabel: 'Demo catalog',
    addedAt: '2026-09-15',
  },
  {
    slug: 'pdf',
    name: 'pdf',
    kind: 'skill',
    craft: 'Content',
    tagline: 'Read, fill, and build PDF files.',
    description:
      'Extracts text and tables, fills forms, merges and splits documents, and OCRs scans so they become searchable. Handles the whole PDF lifecycle.',
    triggers: ['pdf', 'extract text', 'fill form', 'merge pdf', 'ocr'],
    command: 'npx skills add pdf',
    commandLabel: 'Install',
    url: 'https://github.com/anthropics/skills',
    urlLabel: 'Repository',
    license: 'MIT',
    addedAt: '2026-09-08',
  },
  {
    slug: 'docx',
    name: 'docx',
    kind: 'skill',
    craft: 'Content',
    tagline: 'Create and edit Word documents.',
    description:
      'Builds .docx and .dotx files with real structure: tables of contents, headings, page numbers, and letterheads. Also parses and reorganizes existing ones.',
    triggers: ['word document', 'docx', 'report', 'memo', 'template'],
    command: 'npx skills add docx',
    commandLabel: 'Install',
    url: 'https://github.com/anthropics/skills',
    urlLabel: 'Repository',
    license: 'MIT',
    addedAt: '2026-09-08',
  },
  {
    slug: 'pptx',
    name: 'pptx',
    kind: 'skill',
    craft: 'Content',
    tagline: 'Build and edit slide decks.',
    description:
      'Creates decks from scratch or edits existing ones, including templates, layouts, and speaker notes. Reads text out of a .pptx as readily as it writes one.',
    triggers: ['pptx', 'slides', 'deck', 'presentation', 'pitch deck'],
    command: 'npx skills add pptx',
    commandLabel: 'Install',
    url: 'https://github.com/anthropics/skills',
    urlLabel: 'Repository',
    license: 'MIT',
    addedAt: '2026-09-08',
  },
  {
    slug: 'xlsx',
    name: 'xlsx',
    kind: 'skill',
    craft: 'Content',
    tagline: 'Spreadsheets with formulas, not text.',
    description:
      'Writes real formulas, formatting, and charts into .xlsx files, and cleans messy tabular data into something a spreadsheet app can actually open.',
    triggers: ['xlsx', 'spreadsheet', 'csv', 'formulas', 'excel'],
    command: 'npx skills add xlsx',
    commandLabel: 'Install',
    url: 'https://github.com/anthropics/skills',
    urlLabel: 'Repository',
    license: 'MIT',
    addedAt: '2026-09-08',
  },
  {
    slug: 'mcp-builder',
    name: 'mcp-builder',
    kind: 'skill',
    craft: 'DevEx',
    tagline: 'Build MCP servers that hold up.',
    description:
      'Guides the design of an MCP server end to end, in Python with FastMCP or TypeScript with the SDK, so tools stay well-scoped and testable.',
    triggers: ['mcp server', 'build mcp', 'fastmcp', 'model context protocol'],
    command: 'npx skills add mcp-builder',
    commandLabel: 'Install',
    url: 'https://github.com/anthropics/skills',
    urlLabel: 'Repository',
    license: 'MIT',
    addedAt: '2026-09-09',
  },
  {
    slug: 'webapp-testing',
    name: 'webapp-testing',
    kind: 'skill',
    craft: 'DevEx',
    tagline: 'Drive a local web app and assert on it.',
    description:
      'Starts a local server, drives the UI with Playwright, and asserts on the rendered DOM so a change is verified in a browser rather than argued about.',
    triggers: ['playwright', 'web app testing', 'e2e', 'browser test'],
    command: 'npx skills add webapp-testing',
    commandLabel: 'Install',
    url: 'https://github.com/anthropics/skills',
    urlLabel: 'Repository',
    license: 'MIT',
    addedAt: '2026-09-09',
  },
  {
    slug: 'brand-guidelines',
    name: 'brand-guidelines',
    kind: 'skill',
    craft: 'Design',
    tagline: 'Apply a brand book to new surfaces.',
    description:
      'Keeps colors, type, and logo treatment consistent when a brand moves onto a surface it was never designed for, such as a landing page or a deck.',
    triggers: ['brand', 'brand book', 'typography', 'logo usage'],
    command: 'npx skills add brand-guidelines',
    commandLabel: 'Install',
    url: 'https://github.com/anthropics/skills',
    urlLabel: 'Repository',
    license: 'MIT',
    addedAt: '2026-09-10',
  },
  {
    slug: 'canvas-design',
    name: 'canvas-design',
    kind: 'skill',
    craft: 'Design',
    tagline: 'Compose posters and static art.',
    description:
      'Lays out posters and static compositions in multiple formats from one brief, keeping the grid and hierarchy intact as the canvas changes shape.',
    triggers: ['poster', 'canvas', 'print design', 'static art'],
    command: 'npx skills add canvas-design',
    commandLabel: 'Install',
    url: 'https://github.com/anthropics/skills',
    urlLabel: 'Repository',
    license: 'MIT',
    addedAt: '2026-09-10',
  },
  {
    slug: 'algorithmic-art',
    name: 'algorithmic-art',
    kind: 'skill',
    craft: 'Design',
    tagline: 'Generative art with a fixed seed.',
    description:
      'Writes code that draws, with seeded randomness so the output is reproducible and a variation can be tuned instead of re-rolled by luck.',
    triggers: ['generative art', 'creative coding', 'p5', 'seeded random'],
    command: 'npx skills add algorithmic-art',
    commandLabel: 'Install',
    url: 'https://github.com/anthropics/skills',
    urlLabel: 'Repository',
    license: 'MIT',
    addedAt: '2026-09-11',
  },
  {
    slug: 'theme-factory',
    name: 'theme-factory',
    kind: 'skill',
    craft: 'Design',
    tagline: 'Build a theme from a set of tokens.',
    description:
      'Turns a short list of color and type decisions into a complete token set that a design system can consume without a second round of guessing.',
    triggers: ['theme', 'design tokens', 'color system', 'styling'],
    command: 'npx skills add theme-factory',
    commandLabel: 'Install',
    url: 'https://github.com/anthropics/skills',
    urlLabel: 'Repository',
    license: 'MIT',
    addedAt: '2026-09-11',
  },
  {
    slug: 'deep-research',
    name: 'deep-research',
    kind: 'skill',
    craft: 'Research',
    tagline: 'Synthesize sources into a brief.',
    description:
      'Reads across many sources, separates signal from noise, and returns a cited brief with the open questions still marked as open. Built for decisions.',
    triggers: ['research', 'sources', 'brief', 'literature review'],
    command: 'npx skills add deep-research',
    commandLabel: 'Install',
    url: 'https://github.com/aniruddhaadak/wow-repo',
    urlLabel: 'Demo catalog',
    addedAt: '2026-10-01',
    featured: true,
  },
  {
    slug: 'data-viz-field-guide',
    name: 'data-viz-field-guide',
    kind: 'skill',
    craft: 'Research',
    tagline: 'Charts that respect the data.',
    description:
      'Matches chart type to the question being asked, then audits axes, labels, and color encoding for honesty. Decoration without information gets removed.',
    triggers: ['data visualization', 'chart', 'dashboard', 'graphs', 'plot'],
    command: 'npx skills add data-viz-field-guide',
    commandLabel: 'Install',
    url: 'https://github.com/aniruddhaadak/wow-repo',
    urlLabel: 'Demo catalog',
    addedAt: '2026-09-17',
  },
  {
    slug: 'thread-writer',
    name: 'thread-writer',
    kind: 'skill',
    craft: 'Content',
    tagline: 'Multi-part threads that hold attention.',
    description:
      'Breaks one idea into a sequenced thread with a strong opener, a middle that pays off, and a closer that earns the share. Each part stays inside its platform cap.',
    triggers: ['thread', 'twitter thread', 'linkedin thread', 'series', 'multi-part'],
    command: 'npx skills add thread-writer',
    commandLabel: 'Install',
    url: 'https://github.com/aniruddhaadak/wow-repo',
    urlLabel: 'Demo catalog',
    addedAt: '2026-09-27',
  },
  {
    slug: 'copy-edit-pass',
    name: 'copy-edit-pass',
    kind: 'skill',
    craft: 'Content',
    tagline: 'Copy edits that keep your voice.',
    description:
      'Edits for clarity and rhythm without flattening the author. Flags AI tells, vague claims, and sentences that trail off before anyone else reads them.',
    triggers: ['copy edit', 'rewrite', 'proofread', 'tone', 'clarity'],
    command: 'npx skills add copy-edit-pass',
    commandLabel: 'Install',
    url: 'https://github.com/aniruddhaadak/wow-repo',
    urlLabel: 'Demo catalog',
    addedAt: '2026-09-23',
  },
  {
    slug: 'seo-auditor',
    name: 'seo-auditor',
    kind: 'skill',
    craft: 'Content',
    tagline: 'Technical SEO diagnostics that stick.',
    description:
      'Crawls a site for broken metadata, heading drift, and indexation problems, then reports the exact fix for each finding rather than just raising the flag.',
    triggers: ['seo', 'audit', 'meta tags', 'indexing', 'ranking'],
    command: 'npx skills add seo-auditor',
    commandLabel: 'Install',
    url: 'https://github.com/aniruddhaadak/wow-repo',
    urlLabel: 'Demo catalog',
    addedAt: '2026-09-30',
  },
  {
    slug: 'video-gen-director',
    name: 'video-gen-director',
    kind: 'skill',
    craft: 'Multimedia',
    tagline: 'Script-to-screen AI video.',
    description:
      'Turns a script into a shot list, picks the right model per scene, and keeps the motion motivated. Handles aspect ratios and captions per platform.',
    triggers: ['video', 'ai video', 'script', 'shot list', 'veo'],
    command: 'npx skills add video-gen-director',
    commandLabel: 'Install',
    url: 'https://github.com/aniruddhaadak/wow-repo',
    urlLabel: 'Demo catalog',
    addedAt: '2026-09-20',
  },
]

const PROTOCOLS: RegistryEntry[] = [
  {
    slug: 'model-context-protocol',
    name: 'Model Context Protocol',
    kind: 'protocol',
    craft: 'DevEx',
    tagline: 'The open standard for agent tools.',
    description:
      'An open protocol for connecting assistants to tools, data, and prompts over JSON-RPC. One server implementation works across every client that speaks it.',
    triggers: ['mcp', 'tools', 'json-rpc', 'context', 'tool calling'],
    command: 'https://modelcontextprotocol.io/specification',
    commandLabel: 'Specification',
    url: 'https://modelcontextprotocol.io',
    urlLabel: 'Documentation',
    license: 'MIT',
    addedAt: '2026-09-04',
    featured: true,
  },
  {
    slug: 'a2a',
    name: 'Agent2Agent',
    kind: 'protocol',
    craft: 'DevEx',
    tagline: 'Agents talking to agents.',
    description:
      'A protocol for agents built by different vendors to discover each other, negotiate tasks, and collaborate behind one user interface.',
    triggers: ['a2a', 'multi-agent', 'agent card', 'task delegation'],
    command: 'https://a2a-protocol.org/latest/specification/',
    commandLabel: 'Specification',
    url: 'https://a2a-protocol.org',
    urlLabel: 'Documentation',
    license: 'Apache-2.0',
    addedAt: '2026-08-30',
  },
  {
    slug: 'agent-client-protocol',
    name: 'Agent Client Protocol',
    kind: 'protocol',
    craft: 'DevEx',
    tagline: 'Editors and agents, one contract.',
    description:
      'A protocol that lets any code editor drive any coding agent, so the client and the agent can be swapped independently.',
    triggers: ['acp', 'editor integration', 'zed', 'client protocol'],
    command: 'https://agentclientprotocol.com/protocol/overview',
    commandLabel: 'Specification',
    url: 'https://agentclientprotocol.com',
    urlLabel: 'Documentation',
    license: 'Apache-2.0',
    addedAt: '2026-08-27',
  },
  {
    slug: 'ag-ui',
    name: 'AG-UI',
    kind: 'protocol',
    craft: 'DevEx',
    tagline: 'The agent and user interface layer.',
    description:
      'A lightweight event protocol for streaming agent state into a frontend, so an interface can render thinking, tool calls, and results as they arrive.',
    triggers: ['ag-ui', 'streaming', 'frontend events', 'agent ui'],
    command: 'https://docs.ag-ui.com/introduction',
    commandLabel: 'Documentation',
    url: 'https://docs.ag-ui.com',
    urlLabel: 'Documentation',
    license: 'MIT',
    addedAt: '2026-08-24',
  },
  {
    slug: 'agent-skills',
    name: 'Agent Skills',
    kind: 'protocol',
    craft: 'DevEx',
    tagline: 'SKILL.md as a portable capability.',
    description:
      'A folder convention where a SKILL.md file with frontmatter describes one capability, its triggers, and how to run it. Any harness that reads the folder can use it.',
    triggers: ['skill.md', 'agent skills', 'frontmatter', 'progressive disclosure'],
    command: 'https://github.com/anthropics/skills',
    commandLabel: 'Repository',
    url: 'https://www.anthropic.com/news/skills',
    urlLabel: 'Announcement',
    addedAt: '2026-09-05',
  },
  {
    slug: 'json-rpc',
    name: 'JSON-RPC 2.0',
    kind: 'protocol',
    craft: 'DevEx',
    tagline: 'The transport MCP is built on.',
    description:
      'A stateless, light-weight remote procedure call protocol using JSON. MCP runs over it, over stdio or Streamable HTTP.',
    triggers: ['json-rpc', 'rpc', 'transport', 'stdio', 'streamable http'],
    command: 'https://www.jsonrpc.org/specification',
    commandLabel: 'Specification',
    url: 'https://en.wikipedia.org/wiki/JSON-RPC',
    urlLabel: 'Background',
    addedAt: '2026-08-20',
  },
  {
    slug: 'language-server-protocol',
    name: 'Language Server Protocol',
    kind: 'protocol',
    craft: 'DevEx',
    tagline: 'One server, every editor.',
    description:
      'The protocol that decoupled language intelligence from editors, and the pattern MCP was modeled on: implement once, consume from any client.',
    triggers: ['lsp', 'language server', 'editor protocol', 'diagnostics'],
    command:
      'https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/',
    commandLabel: 'Specification',
    url: 'https://microsoft.github.io/language-server-protocol/',
    urlLabel: 'Documentation',
    license: 'MIT',
    addedAt: '2026-08-18',
  },
  {
    slug: 'openapi',
    name: 'OpenAPI Specification',
    kind: 'protocol',
    craft: 'DevEx',
    tagline: 'Describe an HTTP API once.',
    description:
      'A vendor-neutral description format for HTTP APIs. Feed a spec to an agent and it gets typed tools without scraping docs or guessing parameters.',
    triggers: ['openapi', 'swagger', 'api schema', 'rest contract'],
    command: 'https://spec.openapis.org/oas/v3.1.0',
    commandLabel: 'Specification',
    url: 'https://www.openapis.org',
    urlLabel: 'Documentation',
    license: 'Apache-2.0',
    addedAt: '2026-08-15',
  },
  {
    slug: 'webmcp',
    name: 'WebMCP',
    kind: 'protocol',
    craft: 'DevEx',
    tagline: 'Web pages as callable tools.',
    description:
      'A W3C Community Group draft that lets a page expose its own actions as tools, so an agent can operate a site natively instead of driving a browser.',
    triggers: ['webmcp', 'w3c', 'browser tools', 'page actions'],
    command: 'https://github.com/webmachinelearning/webmcp',
    commandLabel: 'Draft',
    url: 'https://webmachinelearning.github.io/webmcp/',
    urlLabel: 'Documentation',
    addedAt: '2026-09-02',
  },
]

const MCP_SERVERS: RegistryEntry[] = [
  {
    slug: 'mcp-filesystem',
    name: 'Filesystem MCP',
    kind: 'mcp',
    craft: 'DevEx',
    tagline: 'Scoped read and write to a directory.',
    description:
      'The reference server for giving an agent file access. Point it at one root directory and everything outside that root stays invisible.',
    triggers: ['filesystem', 'files', 'read write', 'reference server'],
    command: 'npx -y @modelcontextprotocol/server-filesystem ~/projects',
    commandLabel: 'Run',
    url: 'https://github.com/modelcontextprotocol/servers',
    urlLabel: 'Repository',
    license: 'MIT',
    addedAt: '2026-08-12',
  },
  {
    slug: 'mcp-github',
    name: 'GitHub MCP',
    kind: 'mcp',
    craft: 'DevEx',
    tagline: 'Repos, issues, and PRs as tools.',
    description:
      'The official GitHub server. An agent can read a repository, open an issue, review a pull request, and search code without a bespoke integration.',
    triggers: ['github', 'repository', 'issues', 'pull request', 'code search'],
    command: 'docker run -i --rm -e GITHUB_PERSONAL_ACCESS_TOKEN ghcr.io/github/github-mcp-server',
    commandLabel: 'Run',
    url: 'https://github.com/github/github-mcp-server',
    urlLabel: 'Repository',
    license: 'MIT',
    addedAt: '2026-08-12',
    featured: true,
  },
  {
    slug: 'mcp-fetch',
    name: 'Fetch MCP',
    kind: 'mcp',
    craft: 'Research',
    tagline: 'Turn a URL into readable markdown.',
    description:
      'Fetches a page, converts it to markdown, and chunks it for a context window. The default way to hand an agent the open web.',
    triggers: ['fetch', 'web page', 'markdown', 'url', 'crawl'],
    command: 'uvx mcp-server-fetch',
    commandLabel: 'Run',
    url: 'https://github.com/modelcontextprotocol/servers',
    urlLabel: 'Repository',
    license: 'MIT',
    addedAt: '2026-08-13',
  },
  {
    slug: 'mcp-postgres',
    name: 'Postgres MCP',
    kind: 'mcp',
    craft: 'DevEx',
    tagline: 'Read-only by default, on purpose.',
    description:
      'Gives an agent a Postgres connection with a schema it can inspect. Ships restricted to read-only access unless you deliberately widen it.',
    triggers: ['postgres', 'sql', 'database', 'schema inspection'],
    command: 'npx -y @modelcontextprotocol/server-postgres postgresql://localhost/mydb',
    commandLabel: 'Run',
    url: 'https://github.com/modelcontextprotocol/servers',
    urlLabel: 'Repository',
    license: 'MIT',
    addedAt: '2026-08-14',
  },
  {
    slug: 'mcp-sqlite',
    name: 'SQLite MCP',
    kind: 'mcp',
    craft: 'DevEx',
    tagline: 'A whole database in one file.',
    description:
      'Runs SQL against a SQLite database and includes analysis tooling. Useful for local datasets and for demos that need no server at all.',
    triggers: ['sqlite', 'sql', 'local database', 'embedded'],
    command: 'uvx mcp-server-sqlite --db-path ~/data.db',
    commandLabel: 'Run',
    url: 'https://github.com/modelcontextprotocol/servers',
    urlLabel: 'Repository',
    license: 'MIT',
    addedAt: '2026-08-14',
  },
  {
    slug: 'mcp-memory',
    name: 'Memory MCP',
    kind: 'mcp',
    craft: 'DevEx',
    tagline: 'A knowledge graph that survives a restart.',
    description:
      'Stores entities, relations, and observations in a local JSON file so an agent can carry context between sessions instead of starting blank.',
    triggers: ['memory', 'knowledge graph', 'persistence', 'entities'],
    command: 'npx -y @modelcontextprotocol/server-memory',
    commandLabel: 'Run',
    url: 'https://github.com/modelcontextprotocol/servers',
    urlLabel: 'Repository',
    license: 'MIT',
    addedAt: '2026-08-15',
  },
  {
    slug: 'mcp-brave-search',
    name: 'Brave Search MCP',
    kind: 'mcp',
    craft: 'Research',
    tagline: 'Web and news search for an agent.',
    description:
      'Adds web and news search with count and offset pagination, plus a summariser for second-hop queries on a result page.',
    triggers: ['search', 'brave', 'web search', 'news'],
    command: 'npx -y @modelcontextprotocol/server-brave-search',
    commandLabel: 'Run',
    url: 'https://github.com/modelcontextprotocol/servers',
    urlLabel: 'Repository',
    license: 'MIT',
    addedAt: '2026-08-16',
  },
  {
    slug: 'mcp-playwright',
    name: 'Playwright MCP',
    kind: 'mcp',
    craft: 'DevEx',
    tagline: 'Real browser control via accessibility tree.',
    description:
      'Drives a real Chromium browser and exposes an accessibility snapshot rather than pixels, so an agent can navigate and assert without screenshots.',
    triggers: ['playwright', 'browser automation', 'accessibility tree', 'testing'],
    command: 'npx @playwright/mcp@latest',
    commandLabel: 'Run',
    url: 'https://github.com/microsoft/playwright-mcp',
    urlLabel: 'Repository',
    license: 'Apache-2.0',
    addedAt: '2026-08-17',
  },
  {
    slug: 'mcp-chrome-devtools',
    name: 'Chrome DevTools MCP',
    kind: 'mcp',
    craft: 'DevEx',
    tagline: 'Debug a live page from the agent.',
    description:
      'Exposes performance traces, console output, network requests, and script evaluation against the Chrome you already have open.',
    triggers: ['chrome devtools', 'performance trace', 'console', 'network'],
    command: 'npx chrome-devtools-mcp@latest',
    commandLabel: 'Run',
    url: 'https://github.com/ChromeDevTools/chrome-devtools-mcp',
    urlLabel: 'Repository',
    license: 'Apache-2.0',
    addedAt: '2026-08-18',
  },
  {
    slug: 'mcp-context7',
    name: 'Context7',
    kind: 'mcp',
    craft: 'DevEx',
    tagline: 'Current library docs, not training data.',
    description:
      'Pulls version-specific documentation for a library straight into the context window, so code is written against the API that actually exists.',
    triggers: ['documentation', 'library docs', 'versioned', 'upstash'],
    command: 'npx -y @upstash/context7-mcp',
    commandLabel: 'Run',
    url: 'https://github.com/upstash/context7',
    urlLabel: 'Repository',
    addedAt: '2026-08-19',
  },
  {
    slug: 'mcp-firecrawl',
    name: 'Firecrawl MCP',
    kind: 'mcp',
    craft: 'Research',
    tagline: 'Scrape and crawl at scale.',
    description:
      'Turns any site into clean markdown, handles JavaScript rendering and anti-bot measures, and supports deep crawling of a site section.',
    triggers: ['scraping', 'crawling', 'firecrawl', 'site to markdown'],
    command: 'npx -y firecrawl-mcp',
    commandLabel: 'Run',
    url: 'https://github.com/firecrawl/firecrawl-mcp-server',
    urlLabel: 'Repository',
    addedAt: '2026-08-20',
  },
  {
    slug: 'mcp-exa',
    name: 'Exa MCP',
    kind: 'mcp',
    craft: 'Research',
    tagline: 'Neural web search and page contents.',
    description:
      'A search index built on embeddings rather than keywords, with tools to fetch the contents of specific URLs found in the results.',
    triggers: ['exa', 'neural search', 'web search', 'embeddings'],
    command: 'npx -y exa-mcp-server',
    commandLabel: 'Run',
    url: 'https://github.com/exa-labs/exa-mcp-server',
    urlLabel: 'Repository',
    addedAt: '2026-08-21',
  },
  {
    slug: 'mcp-tavily',
    name: 'Tavily MCP',
    kind: 'mcp',
    craft: 'Research',
    tagline: 'Search built for agents, not humans.',
    description:
      'A search API tuned for model consumption, returning concise extracted answers alongside raw results rather than a page of links.',
    triggers: ['tavily', 'search', 'extraction', 'agent search'],
    command: 'npx -y tavily-mcp',
    commandLabel: 'Run',
    url: 'https://github.com/tavily-ai/tavily-mcp',
    urlLabel: 'Repository',
    addedAt: '2026-08-22',
  },
  {
    slug: 'mcp-sentry',
    name: 'Sentry MCP',
    kind: 'mcp',
    craft: 'DevEx',
    tagline: 'Errors and issues, queryable.',
    description:
      'Queries Sentry issues, stack traces, and analysis so an agent can start a fix from the actual crash rather than from a bug report.',
    triggers: ['sentry', 'error tracking', 'stack trace', 'issues'],
    command: 'npx -y @sentry/mcp-server',
    commandLabel: 'Run',
    url: 'https://github.com/getsentry/sentry-mcp',
    urlLabel: 'Repository',
    addedAt: '2026-08-23',
  },
  {
    slug: 'mcp-supabase',
    name: 'Supabase MCP',
    kind: 'mcp',
    craft: 'DevEx',
    tagline: 'Postgres, auth, and storage as tools.',
    description:
      'Exposes a Supabase project database schema, management API, logs, storage, and Edge Functions to an agent that owns the project.',
    triggers: ['supabase', 'postgres', 'storage', 'edge functions', 'auth'],
    command: 'npx -y @supabase/mcp-server-supabase@latest --project-ref=<ref>',
    commandLabel: 'Run',
    url: 'https://github.com/supabase-community/supabase-mcp',
    urlLabel: 'Repository',
    addedAt: '2026-08-24',
  },
  {
    slug: 'mcp-notion',
    name: 'Notion MCP',
    kind: 'mcp',
    craft: 'Content',
    tagline: 'Search and edit a Notion workspace.',
    description:
      'A remote MCP server hosted by Notion. Authenticate once over OAuth and the agent can search pages, read content, and create entries.',
    triggers: ['notion', 'wiki', 'docs', 'oauth', 'remote mcp'],
    command: 'https://mcp.notion.com/mcp',
    commandLabel: 'Endpoint',
    url: 'https://developers.notion.com/docs/mcp',
    urlLabel: 'Documentation',
    addedAt: '2026-08-25',
  },
  {
    slug: 'mcp-stripe',
    name: 'Stripe MCP',
    kind: 'mcp',
    craft: 'DevEx',
    tagline: 'Payments data, read and written safely.',
    description:
      'A remote server over the Stripe API with tool-level restrictions, so an agent can read revenue data without being able to refund a customer by accident.',
    triggers: ['stripe', 'payments', 'billing', 'remote mcp'],
    command: 'https://mcp.stripe.com',
    commandLabel: 'Endpoint',
    url: 'https://docs.stripe.com/mcp',
    urlLabel: 'Documentation',
    addedAt: '2026-08-26',
  },
  {
    slug: 'mcp-huggingface',
    name: 'Hugging Face MCP',
    kind: 'mcp',
    craft: 'Multimedia',
    tagline: 'Search models, datasets, and papers.',
    description:
      'A remote server over the Hugging Face Hub, with tools for semantic search over models and datasets plus paper search for the literature.',
    triggers: ['hugging face', 'models', 'datasets', 'papers', 'semantic search'],
    command: 'https://huggingface.co/mcp',
    commandLabel: 'Endpoint',
    url: 'https://huggingface.co/mcp',
    urlLabel: 'Documentation',
    addedAt: '2026-08-27',
  },
]

const APIS: RegistryEntry[] = [
  {
    slug: 'github-rest-api',
    name: 'GitHub REST API',
    kind: 'api',
    craft: 'DevEx',
    tagline: 'Everything in a repository, over HTTP.',
    description:
      'Read and write repositories, issues, pull requests, actions, and search. The surface most developer tools are built on.',
    triggers: ['github', 'rest api', 'repositories', 'issues', 'webhooks'],
    command: 'https://api.github.com',
    commandLabel: 'Endpoint',
    url: 'https://docs.github.com/rest',
    urlLabel: 'Documentation',
    addedAt: '2026-08-06',
  },
  {
    slug: 'anthropic-api',
    name: 'Anthropic Messages API',
    kind: 'api',
    craft: 'DevEx',
    tagline: 'Claude with tools and streaming.',
    description:
      'One endpoint for messages, tool use, extended thinking, and batches, with streaming over server-sent events.',
    triggers: ['claude', 'anthropic', 'messages', 'tool use', 'streaming'],
    command: 'https://api.anthropic.com/v1/messages',
    commandLabel: 'Endpoint',
    url: 'https://docs.anthropic.com/en/api',
    urlLabel: 'Documentation',
    addedAt: '2026-08-07',
    featured: true,
  },
  {
    slug: 'openai-api',
    name: 'OpenAI API',
    kind: 'api',
    craft: 'DevEx',
    tagline: 'Chat, embeddings, images, realtime.',
    description:
      'The widest surface of any model provider: responses, embeddings, image generation, speech, and a realtime websocket API.',
    triggers: ['openai', 'chat completions', 'embeddings', 'realtime', 'responses'],
    command: 'https://api.openai.com/v1/responses',
    commandLabel: 'Endpoint',
    url: 'https://platform.openai.com/docs/api-reference',
    urlLabel: 'Documentation',
    addedAt: '2026-08-07',
  },
  {
    slug: 'openrouter-api',
    name: 'OpenRouter API',
    kind: 'api',
    craft: 'DevEx',
    tagline: 'One key, every model.',
    description:
      'An OpenAI-compatible gateway over hundreds of models from many providers, with per-model pricing and automatic fallbacks.',
    triggers: ['openrouter', 'gateway', 'model routing', 'openai compatible'],
    command: 'https://openrouter.ai/api/v1/chat/completions',
    commandLabel: 'Endpoint',
    url: 'https://openrouter.ai/api/v1',
    urlLabel: 'Documentation',
    addedAt: '2026-08-08',
  },
  {
    slug: 'groq-api',
    name: 'Groq API',
    kind: 'api',
    craft: 'DevEx',
    tagline: 'Open models at very high tokens per second.',
    description:
      'An inference API on custom silicon, tuned for latency. Best when an agent loop needs a fast cheap model for its inner steps.',
    triggers: ['groq', 'inference', 'low latency', 'open models', 'lpu'],
    command: 'https://api.groq.com/openai/v1/chat/completions',
    commandLabel: 'Endpoint',
    url: 'https://console.groq.com/docs/api',
    urlLabel: 'Documentation',
    addedAt: '2026-08-09',
  },
  {
    slug: 'elevenlabs-api',
    name: 'ElevenLabs API',
    kind: 'api',
    craft: 'Multimedia',
    tagline: 'Text to speech that sounds like a person.',
    description:
      'Speech synthesis, voice cloning, and dubbing, with streaming output so audio can start before the full text is generated.',
    triggers: ['text to speech', 'tts', 'voice', 'dubbing', 'elevenlabs'],
    command: 'https://api.elevenlabs.io/v1/text-to-speech',
    commandLabel: 'Endpoint',
    url: 'https://elevenlabs.io/docs/api-reference/text-to-speech',
    urlLabel: 'Documentation',
    addedAt: '2026-08-10',
  },
  {
    slug: 'deepgram-api',
    name: 'Deepgram API',
    kind: 'api',
    craft: 'Multimedia',
    tagline: 'Streaming speech to text.',
    description:
      'Live and prerecorded transcription over a websocket, with diarization and word-level timings for subtitles and captions.',
    triggers: ['speech to text', 'transcription', 'stt', 'diarization', 'captions'],
    command: 'wss://api.deepgram.com/v1/listen',
    commandLabel: 'Endpoint',
    url: 'https://developers.deepgram.com',
    urlLabel: 'Documentation',
    addedAt: '2026-08-11',
  },
  {
    slug: 'hacker-news-api',
    name: 'Hacker News API',
    kind: 'api',
    craft: 'Research',
    tagline: 'Every story and comment, no key.',
    description:
      'An Algolia-powered search endpoint over the whole Hacker News archive, plus the official Firebase API for items and users.',
    triggers: ['hacker news', 'hn', 'algolia', 'search', 'no key'],
    command: 'https://hn.algolia.com/api/v1/search?query=agents',
    commandLabel: 'Endpoint',
    url: 'https://hn.algolia.com/api',
    urlLabel: 'Documentation',
    addedAt: '2026-08-05',
  },
  {
    slug: 'openalex-api',
    name: 'OpenAlex API',
    kind: 'api',
    craft: 'Research',
    tagline: 'A fully open catalog of research.',
    description:
      'An open index of scholarly works, authors, institutions, and concepts, built to replace the paid bibliographic databases.',
    triggers: ['openalex', 'research', 'scholarly', 'bibliography', 'open access'],
    command: 'https://api.openalex.org/works?search=agent',
    commandLabel: 'Endpoint',
    url: 'https://docs.openalex.org',
    urlLabel: 'Documentation',
    license: 'CC0-1.0',
    addedAt: '2026-08-04',
  },
  {
    slug: 'crossref-api',
    name: 'Crossref API',
    kind: 'api',
    craft: 'Research',
    tagline: 'DOI metadata for published work.',
    description:
      'The registration agency for DOIs, exposing metadata for journal articles, books, and conference papers. The polite pool asks for a mailto.',
    triggers: ['crossref', 'doi', 'metadata', 'citations', 'publications'],
    command: 'https://api.crossref.org/works?query=agent',
    commandLabel: 'Endpoint',
    url: 'https://api.crossref.org',
    urlLabel: 'Documentation',
    addedAt: '2026-08-04',
  },
  {
    slug: 'arxiv-api',
    name: 'arXiv API',
    kind: 'api',
    craft: 'Research',
    tagline: 'Preprints and their full text.',
    description:
      'An Atom feed over the arXiv preprint archive. Results are capped at a few thousand records per query, so page rather than request everything.',
    triggers: ['arxiv', 'preprints', 'papers', 'atom feed', 'physics'],
    command: 'http://export.arxiv.org/api/query?search_query=all:agent',
    commandLabel: 'Endpoint',
    url: 'https://info.arxiv.org/help/api/',
    urlLabel: 'Documentation',
    addedAt: '2026-08-03',
  },
  {
    slug: 'wikipedia-api',
    name: 'Wikipedia REST API',
    kind: 'api',
    craft: 'Research',
    tagline: 'Summaries and page content.',
    description:
      'A read-only REST surface plus a MediaWiki Action API for search, page extracts, and revision history across all language editions.',
    triggers: ['wikipedia', 'encyclopedia', 'extracts', 'mediawiki', 'summaries'],
    command: 'https://en.wikipedia.org/api/rest_v1/page/summary/Agent',
    commandLabel: 'Endpoint',
    url: 'https://en.wikipedia.org/api/rest_v1/',
    urlLabel: 'Documentation',
    addedAt: '2026-08-03',
  },
  {
    slug: 'rest-countries-api',
    name: 'REST Countries API',
    kind: 'api',
    craft: 'Research',
    tagline: 'Countries, currencies, and flags.',
    description:
      'Country data by name, code, currency, language, or region, with field filtering so a response stays small enough to be useful.',
    triggers: ['countries', 'currencies', 'flags', 'geography', 'regions'],
    command: 'https://restcountries.com/v3.1/name/india',
    commandLabel: 'Endpoint',
    url: 'https://restcountries.com',
    urlLabel: 'Documentation',
    license: 'MPL-2.0',
    addedAt: '2026-08-02',
  },
  {
    slug: 'open-meteo-api',
    name: 'Open-Meteo API',
    kind: 'api',
    craft: 'Research',
    tagline: 'Weather data with no API key.',
    description:
      'Forecast and historical weather from national meteorological services, free for non-commercial use and usable without a key.',
    triggers: ['weather', 'forecast', 'no key', 'climate', 'open data'],
    command: 'https://api.open-meteo.com/v1/forecast?latitude=22.57&longitude=88.36',
    commandLabel: 'Endpoint',
    url: 'https://open-meteo.com/en/docs',
    urlLabel: 'Documentation',
    license: 'AGPL-3.0',
    addedAt: '2026-08-02',
  },
  {
    slug: 'picsum-api',
    name: 'Picsum API',
    kind: 'api',
    craft: 'Design',
    tagline: 'Seeded placeholder photography.',
    description:
      'Serves Unsplash-sourced photos at any size, and a seed returns the same image every time. This site uses it for its own imagery.',
    triggers: ['picsum', 'placeholder images', 'photos', 'seeded', 'unsplash'],
    command: 'https://picsum.photos/seed/wow-studio-light/2000/1200',
    commandLabel: 'Endpoint',
    url: 'https://picsum.photos',
    urlLabel: 'Documentation',
    addedAt: '2026-08-01',
  },
  {
    slug: 'pexels-api',
    name: 'Pexels API',
    kind: 'api',
    craft: 'Design',
    tagline: 'Free stock photos and video.',
    description:
      'A curated library of free stock photography and video, searchable by keyword and orientation, with attribution-free licensing.',
    triggers: ['pexels', 'stock photos', 'stock video', 'free images', 'media'],
    command: 'https://api.pexels.com/v1/search?query=studio',
    commandLabel: 'Endpoint',
    url: 'https://www.pexels.com/api/',
    urlLabel: 'Documentation',
    addedAt: '2026-08-01',
  },
  {
    slug: 'resend-api',
    name: 'Resend API',
    kind: 'api',
    craft: 'Content',
    tagline: 'Transactional email with React templates.',
    description:
      'Send email over a simple REST endpoint, with JSX templates that render to HTML server-side and webhooks for delivery events.',
    triggers: ['resend', 'email', 'transactional', 'react email', 'webhooks'],
    command: 'https://api.resend.com/emails',
    commandLabel: 'Endpoint',
    url: 'https://resend.com/docs/api-reference/introduction',
    urlLabel: 'Documentation',
    addedAt: '2026-08-01',
  },
  {
    slug: 'stripe-api',
    name: 'Stripe API',
    kind: 'api',
    craft: 'DevEx',
    tagline: 'Payments, subscriptions, billing.',
    description:
      'A consistent REST API over charges, customers, subscriptions, invoices, and the commerce primitives agents now run checkout through.',
    triggers: ['stripe', 'payments', 'subscriptions', 'billing', 'checkout'],
    command: 'https://api.stripe.com/v1/payment_intents',
    commandLabel: 'Endpoint',
    url: 'https://docs.stripe.com/api',
    urlLabel: 'Documentation',
    addedAt: '2026-07-31',
  },
]

const HARNESSES: RegistryEntry[] = [
  {
    slug: 'opencode',
    name: 'OpenCode',
    kind: 'harness',
    craft: 'DevEx',
    tagline: 'A terminal agent that runs anywhere.',
    description:
      'A provider-agnostic coding agent with a terminal UI, a desktop app, and a client and server you can drive over HTTP.',
    triggers: ['opencode', 'terminal agent', 'tui', 'sst', 'provider agnostic'],
    command: 'npm install -g opencode-ai',
    commandLabel: 'Install',
    url: 'https://opencode.ai',
    urlLabel: 'Documentation',
    license: 'MIT',
    addedAt: '2026-09-26',
    featured: true,
  },
  {
    slug: 'claude-code',
    name: 'Claude Code',
    kind: 'harness',
    craft: 'DevEx',
    tagline: 'An agentic CLI for the whole repo.',
    description:
      'Anthropic coding agent for the terminal and the IDE. Reads skills from a skills directory, calls MCP servers, and holds a plan across a long session.',
    triggers: ['claude code', 'cli agent', 'anthropic', 'ide integration'],
    command: 'npm install -g @anthropic-ai/claude-code',
    commandLabel: 'Install',
    url: 'https://docs.anthropic.com/en/docs/claude-code',
    urlLabel: 'Documentation',
    addedAt: '2026-09-26',
  },
  {
    slug: 'codex-cli',
    name: 'Codex CLI',
    kind: 'harness',
    craft: 'DevEx',
    tagline: 'An OpenAI coding agent in the terminal.',
    description:
      'The open-source implementation behind Codex, with sandboxed execution, a config file, and an MCP client for tools.',
    triggers: ['codex', 'openai', 'cli agent', 'sandbox'],
    command: 'npm install -g @openai/codex',
    commandLabel: 'Install',
    url: 'https://github.com/openai/codex',
    urlLabel: 'Repository',
    license: 'Apache-2.0',
    addedAt: '2026-09-25',
  },
  {
    slug: 'gemini-cli',
    name: 'Gemini CLI',
    kind: 'harness',
    craft: 'DevEx',
    tagline: 'An open agent from Google.',
    description:
      'An Apache-2.0 agent with a large context window, built-in search and file tools, and an extension system for adding capabilities.',
    triggers: ['gemini', 'google', 'cli agent', 'extensions'],
    command: 'npm install -g @google/gemini-cli',
    commandLabel: 'Install',
    url: 'https://github.com/google-gemini/gemini-cli',
    urlLabel: 'Repository',
    license: 'Apache-2.0',
    addedAt: '2026-09-24',
  },
  {
    slug: 'cline',
    name: 'Cline',
    kind: 'harness',
    craft: 'DevEx',
    tagline: 'An autonomous agent inside VS Code.',
    description:
      'A VS Code extension that plans and executes changes with approval gates at each step, so a human sees every file write before it lands.',
    triggers: ['cline', 'vscode', 'extension', 'approval gates'],
    command: 'code --install-extension saoudrizwan.claude-dev',
    commandLabel: 'Install',
    url: 'https://github.com/cline/cline',
    urlLabel: 'Repository',
    license: 'Apache-2.0',
    addedAt: '2026-09-23',
  },
  {
    slug: 'aider',
    name: 'Aider',
    kind: 'harness',
    craft: 'DevEx',
    tagline: 'Pair programming with git in the loop.',
    description:
      'The original terminal pair programmer. It edits files, then commits them with a message it writes, so every change is a reviewable diff.',
    triggers: ['aider', 'pair programming', 'git', 'terminal'],
    command: 'python -m pip install aider-chat',
    commandLabel: 'Install',
    url: 'https://aider.chat',
    urlLabel: 'Documentation',
    license: 'Apache-2.0',
    addedAt: '2026-09-22',
  },
  {
    slug: 'goose',
    name: 'Goose',
    kind: 'harness',
    craft: 'DevEx',
    tagline: 'A local agent on your own machine.',
    description:
      'A local-first agent from Block with a desktop UI and an extensible tool system, built to run against local models and local credentials.',
    triggers: ['goose', 'block', 'local first', 'desktop agent'],
    command:
      'curl -fsSL https://github.com/block/goose/releases/download/stable/download_cli.sh | bash',
    commandLabel: 'Install',
    url: 'https://block.github.io/goose/',
    urlLabel: 'Documentation',
    license: 'Apache-2.0',
    addedAt: '2026-09-21',
  },
  {
    slug: 'openhands',
    name: 'OpenHands',
    kind: 'harness',
    craft: 'DevEx',
    tagline: 'An agent with a full sandbox machine.',
    description:
      'Gives the agent a disposable container with a browser, a terminal, and an editor, so it can install, run, and test instead of only writing text.',
    triggers: ['openhands', 'sandbox', 'docker', 'browser agent'],
    command: 'docker pull docker.all-hands.dev/all-hands-ai/runtime:main',
    commandLabel: 'Pull',
    url: 'https://www.all-hands.dev',
    urlLabel: 'Documentation',
    license: 'MIT',
    addedAt: '2026-09-20',
  },
  {
    slug: 'continue',
    name: 'Continue',
    kind: 'harness',
    craft: 'DevEx',
    tagline: 'Autopilots and chat inside your IDE.',
    description:
      'An IDE extension for VS Code and JetBrains that wires any model into autocomplete and chat, with rules and MCP servers you configure.',
    triggers: ['continue', 'ide', 'autocomplete', 'jetbrains', 'vscode'],
    command: 'code --install-extension Continue.continue',
    commandLabel: 'Install',
    url: 'https://continue.dev',
    urlLabel: 'Documentation',
    license: 'Apache-2.0',
    addedAt: '2026-09-19',
  },
  {
    slug: 'roo-code',
    name: 'Roo Code',
    kind: 'harness',
    craft: 'DevEx',
    tagline: 'An agent with switchable modes.',
    description:
      'A VS Code agent that adds named modes such as architect, code, and debug, each with its own prompt, tools, and file permissions.',
    triggers: ['roo code', 'vscode', 'modes', 'agent roles'],
    command: 'code --install-extension RooVeterinaryInc.roo-cline',
    commandLabel: 'Install',
    url: 'https://github.com/RooCodeInc/Roo-Code',
    urlLabel: 'Repository',
    license: 'Apache-2.0',
    addedAt: '2026-09-18',
  },
  {
    slug: 'zed',
    name: 'Zed',
    kind: 'harness',
    craft: 'DevEx',
    tagline: 'A fast editor with an agent panel.',
    description:
      'A Rust editor built for collaboration and speed, with an agent panel that speaks ACP so agent and editor stay independently swappable.',
    triggers: ['zed', 'editor', 'rust', 'acp', 'collaborative'],
    command: 'brew install --cask zed',
    commandLabel: 'Install',
    url: 'https://zed.dev',
    urlLabel: 'Documentation',
    license: 'GPL-3.0',
    addedAt: '2026-09-17',
  },
  {
    slug: 'swe-agent',
    name: 'SWE-agent',
    kind: 'harness',
    craft: 'Research',
    tagline: 'The academic agent for SWE-bench.',
    description:
      'The Princeton agent-computer interface behind the SWE-bench results, with a paper and a YAML-configurable command interface.',
    triggers: ['swe-agent', 'swe-bench', 'research agent', 'academic'],
    command: 'python -m pip install sweagent',
    commandLabel: 'Install',
    url: 'https://github.com/SWE-agent/SWE-agent',
    urlLabel: 'Repository',
    license: 'MIT',
    addedAt: '2026-09-16',
  },
]

const SOFTWARE: RegistryEntry[] = [
  {
    slug: 'bun',
    name: 'Bun',
    kind: 'software',
    craft: 'DevEx',
    tagline: 'One toolkit for a whole JS project.',
    description:
      'A runtime, bundler, package manager, and test runner in a single binary. A drop-in for Node in most projects, with a much faster cold start.',
    triggers: ['bun', 'runtime', 'bundler', 'package manager', 'javascript'],
    command: 'npm install -g bun',
    commandLabel: 'Install',
    url: 'https://bun.com',
    urlLabel: 'Documentation',
    license: 'MIT',
    addedAt: '2026-09-12',
    featured: true,
  },
  {
    slug: 'nodejs',
    name: 'Node.js',
    kind: 'software',
    craft: 'DevEx',
    tagline: 'The runtime half the web runs on.',
    description:
      'The V8-based JavaScript runtime, and still the default target for serverless functions, CLI tools, and build pipelines.',
    triggers: ['node', 'runtime', 'v8', 'javascript', 'npm'],
    command: 'nvm install --lts',
    commandLabel: 'Install',
    url: 'https://nodejs.org',
    urlLabel: 'Documentation',
    license: 'MIT',
    addedAt: '2026-09-12',
  },
  {
    slug: 'deno',
    name: 'Deno',
    kind: 'software',
    craft: 'DevEx',
    tagline: 'Secure TypeScript with web APIs.',
    description:
      'A TypeScript-first runtime with permissions off by default, a standard library, and the same web APIs a browser exposes.',
    triggers: ['deno', 'runtime', 'typescript', 'permissions', 'secure'],
    command: 'brew install deno',
    commandLabel: 'Install',
    url: 'https://deno.com',
    urlLabel: 'Documentation',
    license: 'MIT',
    addedAt: '2026-09-12',
  },
  {
    slug: 'python',
    name: 'Python',
    kind: 'software',
    craft: 'DevEx',
    tagline: 'The default language of ML tooling.',
    description:
      'The language most agent, model, and data tooling is written in first, with a package index nothing else matches.',
    triggers: ['python', 'pip', 'ml', 'scripting', 'venv'],
    command: 'brew install python',
    commandLabel: 'Install',
    url: 'https://www.python.org',
    urlLabel: 'Documentation',
    license: 'PSF-2.0',
    addedAt: '2026-09-12',
  },
  {
    slug: 'ripgrep',
    name: 'ripgrep',
    kind: 'software',
    craft: 'DevEx',
    tagline: 'Search a codebase faster than you can blink.',
    description:
      'A line-oriented search tool that respects gitignore by default and uses every core you have. The speed floor agents expect from search.',
    triggers: ['ripgrep', 'rg', 'search', 'grep', 'codebase'],
    command: 'brew install ripgrep',
    commandLabel: 'Install',
    url: 'https://github.com/BurntSushi/ripgrep',
    urlLabel: 'Repository',
    license: 'MIT',
    addedAt: '2026-09-11',
  },
  {
    slug: 'fd',
    name: 'fd',
    kind: 'software',
    craft: 'DevEx',
    tagline: 'A friendlier find.',
    description:
      'A fast alternative to find with sane defaults and a simple syntax. The other half of a fast agent search loop.',
    triggers: ['fd', 'find', 'files', 'search', 'cli'],
    command: 'brew install fd',
    commandLabel: 'Install',
    url: 'https://github.com/sharkdp/fd',
    urlLabel: 'Repository',
    license: 'MIT',
    addedAt: '2026-09-11',
  },
  {
    slug: 'jq',
    name: 'jq',
    kind: 'software',
    craft: 'DevEx',
    tagline: 'Query JSON from the shell.',
    description:
      'A filter language for JSON. Turns a raw API response into a one-line answer, which is usually all an agent actually needs.',
    triggers: ['jq', 'json', 'shell', 'filter', 'api'],
    command: 'brew install jq',
    commandLabel: 'Install',
    url: 'https://jqlang.org',
    urlLabel: 'Documentation',
    license: 'MIT',
    addedAt: '2026-09-11',
  },
  {
    slug: 'git',
    name: 'Git',
    kind: 'software',
    craft: 'DevEx',
    tagline: 'Undo, branch, and prove it.',
    description:
      'Distributed version control, and the review surface every agent change should land on. Nothing else gives a reviewer the diff they need.',
    triggers: ['git', 'version control', 'branch', 'diff', 'commit'],
    command: 'brew install git',
    commandLabel: 'Install',
    url: 'https://git-scm.com',
    urlLabel: 'Documentation',
    license: 'GPL-2.0',
    addedAt: '2026-09-10',
  },
  {
    slug: 'postgresql',
    name: 'PostgreSQL',
    kind: 'software',
    craft: 'DevEx',
    tagline: 'The database that does everything.',
    description:
      'A relational database that also does full-text search, vectors, JSON, and queues. Usually the only database an agent needs.',
    triggers: ['postgres', 'postgresql', 'sql', 'database', 'pgvector'],
    command: 'brew install postgresql@17',
    commandLabel: 'Install',
    url: 'https://www.postgresql.org',
    urlLabel: 'Documentation',
    license: 'PostgreSQL License',
    addedAt: '2026-09-10',
  },
  {
    slug: 'sqlite',
    name: 'SQLite',
    kind: 'software',
    craft: 'DevEx',
    tagline: 'A database in a single file.',
    description:
      'An embedded SQL engine in the public domain. The fastest way to give an agent a durable, queryable dataset with nothing to deploy.',
    triggers: ['sqlite', 'embedded', 'sql', 'database', 'public domain'],
    command: 'brew install sqlite',
    commandLabel: 'Install',
    url: 'https://sqlite.org',
    urlLabel: 'Documentation',
    license: 'Public domain',
    addedAt: '2026-09-10',
  },
  {
    slug: 'duckdb',
    name: 'DuckDB',
    kind: 'software',
    craft: 'Research',
    tagline: 'Analytics on a laptop, in-process.',
    description:
      'An in-process columnar engine that runs OLAP queries over Parquet and CSV directly. The analytics engine analysts actually keep.',
    triggers: ['duckdb', 'olap', 'analytics', 'parquet', 'columnar'],
    command: 'brew install duckdb',
    commandLabel: 'Install',
    url: 'https://duckdb.org',
    urlLabel: 'Documentation',
    license: 'MIT',
    addedAt: '2026-09-09',
  },
  {
    slug: 'valkey',
    name: 'Valkey',
    kind: 'software',
    craft: 'DevEx',
    tagline: 'The open fork of Redis.',
    description:
      'A BSD-licensed key-value store and cache forked from Redis under the Linux Foundation. A drop-in for every Redis client.',
    triggers: ['valkey', 'redis', 'cache', 'key value', 'linux foundation'],
    command: 'brew install valkey',
    commandLabel: 'Install',
    url: 'https://valkey.io',
    urlLabel: 'Documentation',
    license: 'BSD-3-Clause',
    addedAt: '2026-09-09',
  },
  {
    slug: 'pgvector',
    name: 'pgvector',
    kind: 'software',
    craft: 'DevEx',
    tagline: 'Vector search inside Postgres.',
    description:
      'A Postgres extension adding vector types and HNSW and IVFFlat indexes, so embeddings live next to the rows they describe.',
    triggers: ['pgvector', 'embeddings', 'vector search', 'postgres', 'hnsw'],
    command: 'brew install pgvector',
    commandLabel: 'Install',
    url: 'https://github.com/pgvector/pgvector',
    urlLabel: 'Repository',
    license: 'PostgreSQL License',
    addedAt: '2026-09-08',
  },
  {
    slug: 'qdrant',
    name: 'Qdrant',
    kind: 'software',
    craft: 'Research',
    tagline: 'A vector database with real filtering.',
    description:
      'A Rust vector search engine with payload filtering, quantization, and a hosted or self-hosted option. One container to run.',
    triggers: ['qdrant', 'vector database', 'similarity search', 'rust'],
    command: 'docker run -p 6333:6333 qdrant/qdrant',
    commandLabel: 'Run',
    url: 'https://qdrant.tech',
    urlLabel: 'Documentation',
    license: 'Apache-2.0',
    addedAt: '2026-09-08',
  },
  {
    slug: 'chroma',
    name: 'Chroma',
    kind: 'software',
    craft: 'Research',
    tagline: 'The embedding database for prototypes.',
    description:
      'An open-source embedding database with a Python and a JS client, an in-memory mode for tests, and persistence when you need it.',
    triggers: ['chroma', 'embeddings', 'vector store', 'rag', 'python'],
    command: 'uv pip install chromadb',
    commandLabel: 'Install',
    url: 'https://www.trychroma.com',
    urlLabel: 'Documentation',
    license: 'Apache-2.0',
    addedAt: '2026-09-07',
  },
  {
    slug: 'lancedb',
    name: 'LanceDB',
    kind: 'software',
    craft: 'Research',
    tagline: 'Vectors on disk, not in memory.',
    description:
      'An embedded vector database on the Lance columnar format, so an index stays on disk instead of in RAM.',
    triggers: ['lancedb', 'lance', 'embedded vectors', 'columnar'],
    command: 'pip install lancedb',
    commandLabel: 'Install',
    url: 'https://lancedb.github.io/lancedb/',
    urlLabel: 'Documentation',
    license: 'Apache-2.0',
    addedAt: '2026-09-07',
  },
  {
    slug: 'ollama',
    name: 'Ollama',
    kind: 'software',
    craft: 'Multimedia',
    tagline: 'Run open models on your own machine.',
    description:
      'A local model runner with a one-command model pull and an OpenAI-compatible endpoint. The easiest way to keep inference offline.',
    triggers: ['ollama', 'local models', 'llama', 'offline', 'self-hosted'],
    command: 'brew install ollama',
    commandLabel: 'Install',
    url: 'https://ollama.com',
    urlLabel: 'Documentation',
    license: 'MIT',
    addedAt: '2026-09-06',
    featured: true,
  },
  {
    slug: 'llama-cpp',
    name: 'llama.cpp',
    kind: 'software',
    craft: 'Multimedia',
    tagline: 'LLM inference in plain C++ with no deps.',
    description:
      'The reference implementation of GGUF inference, running quantised models on a CPU with no GPU and no framework in sight.',
    triggers: ['llama.cpp', 'gguf', 'quantization', 'cpu inference', 'c++'],
    command: 'brew install llama.cpp',
    commandLabel: 'Install',
    url: 'https://github.com/ggml-org/llama.cpp',
    urlLabel: 'Repository',
    license: 'MIT',
    addedAt: '2026-09-06',
  },
  {
    slug: 'vllm',
    name: 'vLLM',
    kind: 'software',
    craft: 'Multimedia',
    tagline: 'High-throughput serving for open models.',
    description:
      'A serving engine with paged attention and continuous batching, built to fill a GPU with requests without wasting memory.',
    triggers: ['vllm', 'serving', 'throughput', 'gpu', 'inference'],
    command: 'uv pip install vllm',
    commandLabel: 'Install',
    url: 'https://docs.vllm.ai',
    urlLabel: 'Documentation',
    license: 'Apache-2.0',
    addedAt: '2026-09-05',
  },
  {
    slug: 'transformers',
    name: 'Transformers',
    kind: 'software',
    craft: 'Multimedia',
    tagline: 'The library every checkpoints ships in.',
    description:
      'The Hugging Face library for loading and running pretrained models, with pipelines that get a first result in a few lines.',
    triggers: ['transformers', 'hugging face', 'models', 'pipeline', 'torch'],
    command: 'uv pip install transformers',
    commandLabel: 'Install',
    url: 'https://huggingface.co/docs/transformers',
    urlLabel: 'Documentation',
    license: 'Apache-2.0',
    addedAt: '2026-09-05',
  },
  {
    slug: 'pytorch',
    name: 'PyTorch',
    kind: 'software',
    craft: 'Multimedia',
    tagline: 'Dynamic graphs and a huge ecosystem.',
    description:
      'The research framework of record, with eager execution, a large operator set, and the ecosystem every other tool compiles against.',
    triggers: ['pytorch', 'torch', 'deep learning', 'training', 'gpu'],
    command: 'uv pip install torch',
    commandLabel: 'Install',
    url: 'https://pytorch.org',
    urlLabel: 'Documentation',
    license: 'BSD-3-Clause',
    addedAt: '2026-09-04',
  },
  {
    slug: 'neovim',
    name: 'Neovim',
    kind: 'software',
    craft: 'DevEx',
    tagline: 'Vim, extensible in Lua.',
    description:
      'A refactor of Vim with a real plugin API, built-in LSP, and a terminal that agents can drive without fighting the config.',
    triggers: ['neovim', 'vim', 'editor', 'lua', 'lsp'],
    command: 'brew install neovim',
    commandLabel: 'Install',
    url: 'https://neovim.io',
    urlLabel: 'Documentation',
    license: 'Apache-2.0',
    addedAt: '2026-09-03',
  },
  {
    slug: 'biome',
    name: 'Biome',
    kind: 'software',
    craft: 'DevEx',
    tagline: 'Lint and format in one Rust binary.',
    description:
      'A formatter and linter for JS, TS, JSON, and CSS that replaces Prettier and ESLint in one tool and runs in milliseconds.',
    triggers: ['biome', 'linter', 'formatter', 'rust', 'javascript'],
    command: 'brew install biome',
    commandLabel: 'Install',
    url: 'https://biomejs.dev',
    urlLabel: 'Documentation',
    license: 'MIT',
    addedAt: '2026-09-03',
  },
  {
    slug: 'tailwindcss',
    name: 'Tailwind CSS',
    kind: 'software',
    craft: 'DevEx',
    tagline: 'Utility CSS with a real design system.',
    description:
      'A utility-first CSS framework where tokens live in CSS variables, so theming is a token swap rather than a stylesheet rewrite.',
    triggers: ['tailwind', 'css', 'utility first', 'design tokens'],
    command: 'npm install tailwindcss @tailwindcss/cli',
    commandLabel: 'Install',
    url: 'https://tailwindcss.com',
    urlLabel: 'Documentation',
    license: 'MIT',
    addedAt: '2026-09-02',
  },
  {
    slug: 'astro',
    name: 'Astro',
    kind: 'software',
    craft: 'DevEx',
    tagline: 'Content sites that ship almost no JS.',
    description:
      'A framework for content-heavy sites that renders to HTML by default and hydrates islands only where interaction is real.',
    triggers: ['astro', 'islands', 'content site', 'static'],
    command: 'npm create astro@latest',
    commandLabel: 'Create',
    url: 'https://astro.build',
    urlLabel: 'Documentation',
    license: 'MIT',
    addedAt: '2026-09-02',
  },
  {
    slug: 'langgraph',
    name: 'LangGraph',
    kind: 'software',
    craft: 'DevEx',
    tagline: 'Agent loops as explicit graphs.',
    description:
      'A library for modelling an agent as a graph of nodes and edges, with checkpointing and human-in-the-loop interrupts built in.',
    triggers: ['langgraph', 'graphs', 'agent framework', 'checkpointing'],
    command: 'uv pip install langgraph',
    commandLabel: 'Install',
    url: 'https://www.langchain.com/langgraph',
    urlLabel: 'Documentation',
    license: 'MIT',
    addedAt: '2026-09-01',
  },
  {
    slug: 'pydantic-ai',
    name: 'Pydantic AI',
    kind: 'software',
    craft: 'DevEx',
    tagline: 'Typechecked agents in Python.',
    description:
      'A Python agent framework where tools and outputs are typed models, so a schema error is a build failure instead of a runtime surprise.',
    triggers: ['pydantic ai', 'python agents', 'typing', 'validation'],
    command: 'uv pip install pydantic-ai',
    commandLabel: 'Install',
    url: 'https://ai.pydantic.dev',
    urlLabel: 'Documentation',
    license: 'MIT',
    addedAt: '2026-09-01',
  },
]

export const entries: RegistryEntry[] = [
  ...SKILLS,
  ...PROTOCOLS,
  ...MCP_SERVERS,
  ...APIS,
  ...HARNESSES,
  ...SOFTWARE,
]
